In [1]:
import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import Dense

In [3]:
data = pd.read_csv('forestfires.csv')
data.head()

,month,day,FFMC,DMC,DC,ISI,temp,RH,wind,rain,...,monthfeb,monthjan,monthjul,monthjun,monthmar,monthmay,monthnov,monthoct,monthsep,size_category
0,mar,fri,86.2,26.2,94.3,5.1,8.2,51,6.7,0.0,...,0,0,0,0,1,0,0,0,0,small
1,oct,tue,90.6,35.4,669.1,6.7,18.0,33,0.9,0.0,...,0,0,0,0,0,0,0,1,0,small
2,oct,sat,90.6,43.7,686.9,6.7,14.6,33,1.3,0.0,...,0,0,0,0,0,0,0,1,0,small
3,mar,fri,91.7,33.3,77.5,9.0,8.3,97,4.0,0.2,...,0,0,0,0,1,0,0,0,0,small
4,mar,sun,89.3,51.3,102.2,9.6,11.4,99,1.8,0.0,...,0,0,0,0,1,0,0,0,0,small

In [4]:
data1 = data.iloc[:,2:]

In [5]:
data1.head()

,FFMC,DMC,DC,ISI,temp,RH,wind,rain,area,dayfri,...,monthfeb,monthjan,monthjul,monthjun,monthmar,monthmay,monthnov,monthoct,monthsep,size_category
0,86.2,26.2,94.3,5.1,8.2,51,6.7,0.0,0.0,1,...,0,0,0,0,1,0,0,0,0,small
1,90.6,35.4,669.1,6.7,18.0,33,0.9,0.0,0.0,0,...,0,0,0,0,0,0,0,1,0,small
2,90.6,43.7,686.9,6.7,14.6,33,1.3,0.0,0.0,0,...,0,0,0,0,0,0,0,1,0,small
3,91.7,33.3,77.5,9.0,8.3,97,4.0,0.2,0.0,1,...,0,0,0,0,1,0,0,0,0,small
4,89.3,51.3,102.2,9.6,11.4,99,1.8,0.0,0.0,0,...,0,0,0,0,1,0,0,0,0,small

In [6]:
data1['size_category']= data1['size_category'].astype('category')
data1['size_category'] = data1['size_category'].cat.codes

In [7]:
data1

,FFMC,DMC,DC,ISI,temp,RH,wind,rain,area,dayfri,...,monthfeb,monthjan,monthjul,monthjun,monthmar,monthmay,monthnov,monthoct,monthsep,size_category
0,86.2,26.2,94.3,5.1,8.2,51,6.7,0.0,0.00,1,...,0,0,0,0,1,0,0,0,0,1
1,90.6,35.4,669.1,6.7,18.0,33,0.9,0.0,0.00,0,...,0,0,0,0,0,0,0,1,0,1
2,90.6,43.7,686.9,6.7,14.6,33,1.3,0.0,0.00,0,...,0,0,0,0,0,0,0,1,0,1
3,91.7,33.3,77.5,9.0,8.3,97,4.0,0.2,0.00,1,...,0,0,0,0,1,0,0,0,0,1
4,89.3,51.3,102.2,9.6,11.4,99,1.8,0.0,0.00,0,...,0,0,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512,81.6,56.7,665.6,1.9,27.8,32,2.7,0.0,6.44,0,...,0,0,0,0,0,0,0,0,0,0
513,81.6,56.7,665.6,1.9,21.9,71,5.8,0.0,54.29,0,...,0,0,0,0,0,0,0,0,0,0
514,81.6,56.7,665.6,1.9,21.2,70,6.7,0.0,11.16,0,...,0,0,0,0,0,0,0,0,0,0
515,94.4,146.0,614.7,11.3,25.6,42,4.0,0.0,0.00,0,...,0,0,0,0,0,0,0,0,0,1
516,79.5,3.0,106.7,1.1,11.8,31,4.5,0.0,0.00,0,...,0,0,0,0,0,0,1,0,0,1

In [8]:
data1.shape

(517, 29)

In [9]:
data1.describe()

,FFMC,DMC,DC,ISI,temp,RH,wind,rain,area,dayfri,...,monthfeb,monthjan,monthjul,monthjun,monthmar,monthmay,monthnov,monthoct,monthsep,size_category
count,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,...,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000
mean,90.644681,110.872340,547.940039,9.021663,18.889168,44.288201,4.017602,0.021663,12.847292,0.164410,...,0.038685,0.003868,0.061896,0.032882,0.104449,0.003868,0.001934,0.029014,0.332689,0.731141
std,5.520111,64.046482,248.066192,4.559477,5.806625,16.317469,1.791653,0.295959,63.655818,0.371006,...,0.193029,0.062137,0.241199,0.178500,0.306138,0.062137,0.043980,0.168007,0.471632,0.443796
min,18.700000,1.100000,7.900000,0.000000,2.200000,15.000000,0.400000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,90.200000,68.600000,437.700000,6.500000,15.500000,33.000000,2.700000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,91.600000,108.300000,664.200000,8.400000,19.300000,42.000000,4.000000,0.000000,0.520000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,92.900000,142.400000,713.900000,10.800000,22.800000,53.000000,4.900000,0.000000,6.570000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000
max,96.200000,291.300000,860.600000,56.100000,33.300000,100.000000,9.400000,6.400000,1090.840000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [10]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 29 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   FFMC           517 non-null    float64
 1   DMC            517 non-null    float64
 2   DC             517 non-null    float64
 3   ISI            517 non-null    float64
 4   temp           517 non-null    float64
 5   RH             517 non-null    int64
 6   wind           517 non-null    float64
 7   rain           517 non-null    float64
 8   area           517 non-null    float64
 9   dayfri         517 non-null    int64
 10  daymon         517 non-null    int64
 11  daysat         517 non-null    int64
 12  daysun         517 non-null    int64
 13  daythu         517 non-null    int64
 14  daytue         517 non-null    int64
 15  daywed         517 non-null    int64
 16  monthapr       517 non-null    int64
 17  monthaug       517 non-null    int64
 18  monthdec       517 non-null    int64
 19  monthfeb       517 non-null    int64
 20  monthjan       517 non-null    int64
 21  monthjul       517 non-null    int64
 22  monthjun       517 non-null    int64
 23  monthmar       517 non-null    int64
 24  monthmay       517 non-null    int64
 25  monthnov       517 non-null    int64
 26  monthoct       517 non-null    int64
 27  monthsep       517 non-null    int64
 28  size_category  517 non-null    int8
dtypes: float64(8), int64(20), int8(1)
memory usage: 113.7 KB

In [11]:
data1.corr()

,FFMC,DMC,DC,ISI,temp,RH,wind,rain,area,dayfri,...,monthfeb,monthjan,monthjul,monthjun,monthmar,monthmay,monthnov,monthoct,monthsep,size_category
FFMC,1.000000,0.382619,0.330512,0.531805,0.431532,-0.300995,-0.028485,0.056702,0.040122,0.019306,...,-0.281535,-0.454771,0.031833,-0.040634,-0.074327,-0.037230,-0.088964,-0.005998,0.076609,-0.022063
DMC,0.382619,1.000000,0.682192,0.305128,0.469594,0.073795,-0.105342,0.074790,0.072994,-0.012010,...,-0.317899,-0.105647,-0.001946,-0.050403,-0.407404,-0.081980,-0.074218,-0.187632,0.110907,-0.034715
DC,0.330512,0.682192,1.000000,0.229154,0.496208,-0.039192,-0.203466,0.035861,0.049383,-0.004220,...,-0.399277,-0.115064,-0.100887,-0.186183,-0.650427,-0.114209,-0.078380,0.093279,0.531857,-0.019428
ISI,0.531805,0.305128,0.229154,1.000000,0.394287,-0.132517,0.106826,0.067668,0.008258,0.046695,...,-0.249777,-0.103588,0.020982,0.111516,-0.143520,-0.060493,-0.076559,-0.071154,-0.068877,0.008726
temp,0.431532,0.469594,0.496208,0.394287,1.000000,-0.527390,-0.227116,0.069491,0.097844,-0.071949,...,-0.320015,-0.146520,0.142588,0.051015,-0.341797,-0.045540,-0.053798,-0.053513,0.088006,-0.006021
RH,-0.300995,0.073795,-0.039192,-0.132517,-0.527390,1.000000,0.069410,0.099751,-0.075519,0.064506,...,0.140430,0.170923,0.013185,0.009382,-0.089836,0.086822,-0.035885,-0.072334,-0.062596,0.045243
wind,-0.028485,-0.105342,-0.203466,0.106826,-0.227116,0.069410,1.000000,0.061119,0.012317,0.118090,...,-0.029431,-0.070245,-0.040645,0.012124,0.181433,0.015054,0.011864,-0.053850,-0.181476,-0.059113
rain,0.056702,0.074790,0.035861,0.067668,0.069491,0.099751,0.061119,1.000000,-0.007366,-0.004261,...,-0.014698,-0.004566,-0.013390,-0.013510,-0.020744,-0.004566,-0.003225,-0.012665,-0.051733,-0.050001
area,0.040122,0.072994,0.049383,0.008258,0.097844,-0.075519,0.012317,-0.007366,1.000000,-0.052911,...,-0.020732,-0.012589,0.006149,-0.020314,-0.045596,0.006264,-0.008893,-0.016878,0.056573,-0.311322
dayfri,0.019306,-0.012010,-0.004220,0.046695,-0.071949,0.064506,0.118090,-0.004261,-0.052911,1.000000,...,0.046323,-0.027643,-0.048969,0.006000,0.036205,0.056423,-0.019527,-0.045585,0.107671,0.021810
daymon,-0.059396,-0.107921,-0.052993,-0.158601,-0.136529,0.009376,-0.063881,-0.029945,-0.021206,-0.181293,...,0.003933,-0.025470,-0.013300,0.017553,0.077125,-0.025470,-0.017992,0.060975,0.039632,0.011156
daysat,-0.019637,-0.003653,-0.035189,-0.038585,0.034899,-0.023869,-0.063799,-0.032271,0.087868,-0.195372,...,0.020406,0.057019,0.060945,-0.022408,0.021024,0.057019,-0.019390,0.017584,-0.032783,-0.040397
daysun,-0.089517,0.025355,-0.001431,-0.003243,0.014403,0.136220,0.027981,-0.017872,-0.020463,-0.210462,...,0.008416,0.050887,-0.018241,0.024540,-0.047726,-0.029568,-0.020887,0.007252,-0.048817,-0.016429
daythu,0.071730,0.087672,0.051859,-0.022406,0.051432,-0.123061,-0.062553,-0.026798,0.020121,-0.162237,...,-0.042278,-0.022793,-0.019300,-0.000195,-0.026885,-0.022793,-0.016101,-0.063223,0.008984,0.045985
daytue,0.011225,0.000016,0.028368,0.068610,0.035630,-0.014211,0.053396,0.139311,-0.001333,-0.166728,...,-0.014491,-0.023424,0.049688,-0.069308,-0.032351,-0.023424,0.117121,0.005008,-0.028570,-0.036998
daywed,0.093908,0.017939,0.024803,0.125415,0.090580,-0.087508,-0.019965,-0.020744,-0.011452,-0.151487,...,-0.035713,-0.021282,-0.008985,0.043422,-0.033917,-0.021282,-0.015034,0.016325,-0.053222,0.021659
monthapr,-0.117199,-0.197543,-0.268211,-0.106478,-0.157051,0.021235,0.048266,-0.009752,-0.008280,-0.019140,...,-0.026701,-0.008295,-0.034190,-0.024543,-0.045456,-0.008295,-0.005860,-0.023008,-0.093982,0.014001
monthaug,0.228103,0.497928,0.279361,0.334639,0.351404,0.054761,0.028577,0.093101,-0.004187,-0.100837,...,-0.149116,-0.046323,-0.190937,-0.137065,-0.253859,-0.046323,-0.032724,-0.128493,-0.524858,0.058954
monthdec,-0.137044,-0.176301,-0.105642,-0.162322,-0.329648,-0.047714,0.269702,-0.009752,0.001010,-0.019140,...,-0.026701,-0.008295,-0.034190,-0.024543,-0.045456,-0.008295,-0.005860,-0.023008,-0.093982,-0.186140
monthfeb,-0.281535,-0.317899,-0.399277,-0.249777,-0.320015,0.140430,-0.029431,-0.014698,-0.020732,0.046323,...,1.000000,-0.012501,-0.051528,-0.036989,-0.068508,-0.012501,-0.008831,-0.034676,-0.141642,-0.014090
monthjan,-0.454771,-0.105647,-0.115064,-0.103588,-0.146520,0.170923,-0.070245,-0.004566,-0.012589,-0.027643,...,-0.012501,1.000000,-0.016007,-0.011491,-0.021282,-0.003883,-0.002743,-0.010772,-0.044001,0.037790
monthjul,0.031833,-0.001946,-0.100887,0.020982,0.142588,0.013185,-0.040645,-0.013390,0.006149,-0.048969,...,-0.051528,-0.016007,1.000000,-0.047363,-0.087722,-0.016007,-0.011308,-0.044402,-0.181367,-0.007179
monthjun,-0.040634,-0.050403,-0.186183,0.111516,0.051015,0.009382,0.012124,-0.013510,-0.020314,0.006000,...,-0.036989,-0.011491,-0.047363,1.000000,-0.062972,-0.011491,-0.008117,-0.031874,-0.130195,0.038423
monthmar,-0.074327,-0.407404,-0.650427,-0.143520,-0.341797,-0.089836,0.181433,-0.020744,-0.045596,0.036205,...,-0.068508,-0.021282,-0.087722,-0.062972,1.000000,-0.021282,-0.015034,-0.059034,-0.241135,0.035923
monthmay,-0.037230,-0.081980,-0.114209,-0.060493,-0.045540,0.086822,0.015054,-0.004566,0.006264,0.056423,...,-0.012501,-0.003883,-0.016007,-0.011491,-0.021282,1.000000,-0.002743,-0.010772,-0.044001,-0.032488
monthnov,-0.088964,-0.074218,-0.078380,-0.076559,-0.053798,-0.035885,0.011864,-0.003225,-0.008893,-0.019527,...,-0.008831,-0.002743,-0.011308,-0.008117,-0.015034,-0.002743,1.000000,-0.007610,-0.031083,0.026695
monthoct,-0.005998,-0.187632,0.093279,-0.071154,-0.053513,-0.072334,-0.053850,-0.012665,-0.016878,-0.045585,...,-0.034676,-0.010772,-0.044402,-0.031874,-0.059034,-0.010772,-0.007610,1.000000,-0.122053,0.000855
monthsep,0.076609,0.110907,0.531857,-0.068877,0.088006,-0.062596,-0.181476,-0.051733,0.056573,0.107671,...,-0.141642,-0.044001,-0.181367,-0.130195,-0.241135,-0.044001,-0.031083,-0.122053,1.000000,-0.044038
size_category,-0.022063,-0.034715,-0.019428,0.008726,-0.006021,0.045243,-0.059113,-0.050001,-0.311322,0.021810,...,-0.014090,0.037790,-0.007179,0.038423,0.035923,-0.032488,0.026695,0.000855,-0.044038,1.000000

In [12]:
data2 = data1.values

In [13]:
x = data2[:,0:28]
y = data2[:,28]

In [14]:
x

array([[ 86.2,  26.2,  94.3, ...,   0. ,   0. ,   0. ],
       [ 90.6,  35.4, 669.1, ...,   0. ,   1. ,   0. ],
       [ 90.6,  43.7, 686.9, ...,   0. ,   1. ,   0. ],
       ...,
       [ 81.6,  56.7, 665.6, ...,   0. ,   0. ,   0. ],
       [ 94.4, 146. , 614.7, ...,   0. ,   0. ,   0. ],
       [ 79.5,   3. , 106.7, ...,   1. ,   0. ,   0. ]])

In [15]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
       1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0.,
       1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 1., 1.,
       1., 1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1., 0., 0., 1.,
       1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1.,
       0., 0., 1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1.,
       1., 0., 1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 1.,
       0., 0., 1., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 0., 0., 0., 1., 1.])

In [16]:
model = Sequential()
model.add(Dense(12, input_dim = 28, kernel_initializer = 'he_uniform', activation = 'relu'))
model.add(Dense(8, kernel_initializer = 'he_uniform', activation = 'relu'))
model.add(Dense(1, kernel_initializer = 'he_uniform', activation = 'sigmoid'))

In [17]:
model.compile(loss = 'binary_crossentropy',optimizer = 'adam',metrics = ['accuracy'])

In [18]:
model.fit(x,y, validation_split = 0.33, epochs= 150, batch_size = 20)

Epoch 1/150
18/18 [==============================] - 4s 18ms/step - loss: 4.8260 - accuracy: 0.5607 - val_loss: 6.5775 - val_accuracy: 0.6491
Epoch 2/150
18/18 [==============================] - 0s 5ms/step - loss: 2.5281 - accuracy: 0.6879 - val_loss: 2.8407 - val_accuracy: 0.6316
Epoch 3/150
18/18 [==============================] - 0s 5ms/step - loss: 1.6504 - accuracy: 0.6676 - val_loss: 3.2885 - val_accuracy: 0.6608
Epoch 4/150
18/18 [==============================] - 0s 5ms/step - loss: 1.4309 - accuracy: 0.6850 - val_loss: 3.0009 - val_accuracy: 0.6784
Epoch 5/150
18/18 [==============================] - 0s 5ms/step - loss: 1.1438 - accuracy: 0.7486 - val_loss: 1.8889 - val_accuracy: 0.7018
Epoch 6/150
18/18 [==============================] - 0s 5ms/step - loss: 0.7566 - accuracy: 0.7457 - val_loss: 1.5870 - val_accuracy: 0.7368
Epoch 7/150
18/18 [==============================] - 0s 4ms/step - loss: 0.8132 - accuracy: 0.7514 - val_loss: 1.5001 - val_accuracy: 0.7427
Epoch 8/150
18/18 [==============================] - 0s 5ms/step - loss: 0.6360 - accuracy: 0.7572 - val_loss: 1.2424 - val_accuracy: 0.7427
Epoch 9/150
18/18 [==============================] - 0s 4ms/step - loss: 0.5803 - accuracy: 0.7890 - val_loss: 0.7680 - val_accuracy: 0.7485
Epoch 10/150
18/18 [==============================] - 0s 5ms/step - loss: 0.5515 - accuracy: 0.8035 - val_loss: 0.7172 - val_accuracy: 0.7719
Epoch 11/150
18/18 [==============================] - 0s 4ms/step - loss: 0.5524 - accuracy: 0.7977 - val_loss: 0.6406 - val_accuracy: 0.7602
Epoch 12/150
18/18 [==============================] - 0s 5ms/step - loss: 0.4912 - accuracy: 0.8208 - val_loss: 0.7893 - val_accuracy: 0.7719
Epoch 13/150
18/18 [==============================] - 0s 4ms/step - loss: 0.4357 - accuracy: 0.8382 - val_loss: 0.6309 - val_accuracy: 0.7953
Epoch 14/150
18/18 [==============================] - 0s 4ms/step - loss: 0.3970 - accuracy: 0.8410 - val_loss: 0.5422 - val_accuracy: 0.8187
Epoch 15/150
18/18 [==============================] - 0s 5ms/step - loss: 0.3755 - accuracy: 0.8295 - val_loss: 0.6108 - val_accuracy: 0.7953
Epoch 16/150
18/18 [==============================] - 0s 5ms/step - loss: 0.4026 - accuracy: 0.8584 - val_loss: 0.5097 - val_accuracy: 0.8304
Epoch 17/150
18/18 [==============================] - 0s 4ms/step - loss: 0.3613 - accuracy: 0.8613 - val_loss: 0.4685 - val_accuracy: 0.8246
Epoch 18/150
18/18 [==============================] - 0s 5ms/step - loss: 0.3846 - accuracy: 0.8497 - val_loss: 0.9694 - val_accuracy: 0.7719
Epoch 19/150
18/18 [==============================] - 0s 4ms/step - loss: 0.3594 - accuracy: 0.8642 - val_loss: 0.5086 - val_accuracy: 0.8246
Epoch 20/150
18/18 [==============================] - 0s 4ms/step - loss: 0.2962 - accuracy: 0.8757 - val_loss: 0.4105 - val_accuracy: 0.8304
Epoch 21/150
18/18 [==============================] - 0s 4ms/step - loss: 0.2900 - accuracy: 0.8931 - val_loss: 0.4012 - val_accuracy: 0.8421
Epoch 22/150
18/18 [==============================] - 0s 5ms/step - loss: 0.2911 - accuracy: 0.8960 - val_loss: 0.4230 - val_accuracy: 0.8480
Epoch 23/150
18/18 [==============================] - 0s 5ms/step - loss: 0.2708 - accuracy: 0.8931 - val_loss: 0.4877 - val_accuracy: 0.8246
Epoch 24/150
18/18 [==============================] - 0s 5ms/step - loss: 0.2508 - accuracy: 0.9046 - val_loss: 0.4336 - val_accuracy: 0.8304
Epoch 25/150
18/18 [==============================] - 0s 5ms/step - loss: 0.2350 - accuracy: 0.9017 - val_loss: 0.3581 - val_accuracy: 0.8713
Epoch 26/150
18/18 [==============================] - 0s 4ms/step - loss: 0.2742 - accuracy: 0.8931 - val_loss: 0.3430 - val_accuracy: 0.8772
Epoch 27/150
18/18 [==============================] - 0s 5ms/step - loss: 0.2303 - accuracy: 0.8988 - val_loss: 0.3489 - val_accuracy: 0.8596
Epoch 28/150
18/18 [==============================] - 0s 5ms/step - loss: 0.2321 - accuracy: 0.9133 - val_loss: 0.3236 - val_accuracy: 0.8713
Epoch 29/150
18/18 [==============================] - 0s 5ms/step - loss: 0.2251 - accuracy: 0.9133 - val_loss: 0.4572 - val_accuracy: 0.8246
Epoch 30/150
18/18 [==============================] - 0s 4ms/step - loss: 0.2113 - accuracy: 0.9104 - val_loss: 0.4020 - val_accuracy: 0.8304
Epoch 31/150
18/18 [==============================] - 0s 4ms/step - loss: 0.2333 - accuracy: 0.9017 - val_loss: 0.5689 - val_accuracy: 0.8187
Epoch 32/150
18/18 [==============================] - 0s 5ms/step - loss: 0.2245 - accuracy: 0.9075 - val_loss: 0.3595 - val_accuracy: 0.8538
Epoch 33/150
18/18 [==============================] - 0s 5ms/step - loss: 0.2071 - accuracy: 0.9133 - val_loss: 0.3841 - val_accuracy: 0.8363
Epoch 34/150
18/18 [==============================] - 0s 4ms/step - loss: 0.1945 - accuracy: 0.9249 - val_loss: 0.3269 - val_accuracy: 0.8538
Epoch 35/150
18/18 [==============================] - 0s 4ms/step - loss: 0.1835 - accuracy: 0.9306 - val_loss: 0.3959 - val_accuracy: 0.8421
Epoch 36/150
18/18 [==============================] - 0s 4ms/step - loss: 0.1890 - accuracy: 0.9220 - val_loss: 0.2695 - val_accuracy: 0.8830
Epoch 37/150
18/18 [==============================] - 0s 5ms/step - loss: 0.1771 - accuracy: 0.9480 - val_loss: 0.3571 - val_accuracy: 0.8538
Epoch 38/150
18/18 [==============================] - 0s 4ms/step - loss: 0.2159 - accuracy: 0.9220 - val_loss: 0.5581 - val_accuracy: 0.8246
Epoch 39/150
18/18 [==============================] - 0s 4ms/step - loss: 0.2745 - accuracy: 0.8931 - val_loss: 0.3112 - val_accuracy: 0.9123
Epoch 40/150
18/18 [==============================] - 0s 4ms/step - loss: 0.2835 - accuracy: 0.8960 - val_loss: 0.2560 - val_accuracy: 0.8772
Epoch 41/150
18/18 [==============================] - 0s 4ms/step - loss: 0.1611 - accuracy: 0.9451 - val_loss: 0.4004 - val_accuracy: 0.8363
Epoch 42/150
18/18 [==============================] - 0s 5ms/step - loss: 0.1836 - accuracy: 0.9277 - val_loss: 0.2440 - val_accuracy: 0.9298
Epoch 43/150
18/18 [==============================] - 0s 4ms/step - loss: 0.1586 - accuracy: 0.9451 - val_loss: 0.2769 - val_accuracy: 0.8713
Epoch 44/150
18/18 [==============================] - 0s 5ms/step - loss: 0.1456 - accuracy: 0.9480 - val_loss: 0.2329 - val_accuracy: 0.9064
Epoch 45/150
18/18 [==============================] - 0s 6ms/step - loss: 0.1615 - accuracy: 0.9624 - val_loss: 0.2862 - val_accuracy: 0.8713
Epoch 46/150
18/18 [==============================] - 0s 5ms/step - loss: 0.1784 - accuracy: 0.9306 - val_loss: 0.3303 - val_accuracy: 0.8655
Epoch 47/150
18/18 [==============================] - 0s 4ms/step - loss: 0.1443 - accuracy: 0.9509 - val_loss: 0.2345 - val_accuracy: 0.8830
Epoch 48/150
18/18 [==============================] - 0s 4ms/step - loss: 0.1854 - accuracy: 0.9393 - val_loss: 0.2203 - val_accuracy: 0.9181
Epoch 49/150
18/18 [==============================] - 0s 4ms/step - loss: 0.1534 - accuracy: 0.9566 - val_loss: 0.3718 - val_accuracy: 0.8538
Epoch 50/150
18/18 [==============================] - 0s 5ms/step - loss: 0.1542 - accuracy: 0.9538 - val_loss: 0.2988 - val_accuracy: 0.8713
Epoch 51/150
18/18 [==============================] - 0s 4ms/step - loss: 0.1626 - accuracy: 0.9480 - val_loss: 0.2155 - val_accuracy: 0.9357
Epoch 52/150
18/18 [==============================] - 0s 4ms/step - loss: 0.1803 - accuracy: 0.9364 - val_loss: 0.3306 - val_accuracy: 0.8655
Epoch 53/150
18/18 [==============================] - 0s 5ms/step - loss: 0.1432 - accuracy: 0.9566 - val_loss: 0.2116 - val_accuracy: 0.9006
Epoch 54/150
18/18 [==============================] - 0s 4ms/step - loss: 0.1495 - accuracy: 0.9595 - val_loss: 0.3316 - val_accuracy: 0.8713
Epoch 55/150
18/18 [==============================] - 0s 5ms/step - loss: 0.1326 - accuracy: 0.9480 - val_loss: 0.2044 - val_accuracy: 0.9064
Epoch 56/150
18/18 [==============================] - 0s 5ms/step - loss: 0.1492 - accuracy: 0.9509 - val_loss: 0.1981 - val_accuracy: 0.9123
Epoch 57/150
18/18 [==============================] - 0s 5ms/step - loss: 0.1258 - accuracy: 0.9538 - val_loss: 0.2862 - val_accuracy: 0.8713
Epoch 58/150
18/18 [==============================] - 0s 4ms/step - loss: 0.1260 - accuracy: 0.9509 - val_loss: 0.2652 - val_accuracy: 0.8713
Epoch 59/150
18/18 [==============================] - 0s 4ms/step - loss: 0.1245 - accuracy: 0.9624 - val_loss: 0.2210 - val_accuracy: 0.8830
Epoch 60/150
18/18 [==============================] - 0s 4ms/step - loss: 0.1508 - accuracy: 0.9480 - val_loss: 0.4526 - val_accuracy: 0.8363
Epoch 61/150
18/18 [==============================] - 0s 4ms/step - loss: 0.1325 - accuracy: 0.9653 - val_loss: 0.2578 - val_accuracy: 0.8772
Epoch 62/150
18/18 [==============================] - 0s 4ms/step - loss: 0.1098 - accuracy: 0.9653 - val_loss: 0.2122 - val_accuracy: 0.8947
Epoch 63/150
18/18 [==============================] - 0s 5ms/step - loss: 0.1213 - accuracy: 0.9595 - val_loss: 0.2830 - val_accuracy: 0.8713
Epoch 64/150
18/18 [==============================] - 0s 4ms/step - loss: 0.1341 - accuracy: 0.9595 - val_loss: 0.2049 - val_accuracy: 0.9474
Epoch 65/150
18/18 [==============================] - 0s 4ms/step - loss: 0.1303 - accuracy: 0.9653 - val_loss: 0.2126 - val_accuracy: 0.8830
Epoch 66/150
18/18 [==============================] - 0s 4ms/step - loss: 0.1020 - accuracy: 0.9769 - val_loss: 0.2056 - val_accuracy: 0.8947
Epoch 67/150
18/18 [==============================] - 0s 4ms/step - loss: 0.0960 - accuracy: 0.9740 - val_loss: 0.1758 - val_accuracy: 0.9474
Epoch 68/150
18/18 [==============================] - 0s 4ms/step - loss: 0.1080 - accuracy: 0.9740 - val_loss: 0.2091 - val_accuracy: 0.8830
Epoch 69/150
18/18 [==============================] - 0s 5ms/step - loss: 0.1082 - accuracy: 0.9653 - val_loss: 0.1866 - val_accuracy: 0.9064
Epoch 70/150
18/18 [==============================] - 0s 4ms/step - loss: 0.1367 - accuracy: 0.9509 - val_loss: 0.1853 - val_accuracy: 0.9532
Epoch 71/150
18/18 [==============================] - 0s 4ms/step - loss: 0.1141 - accuracy: 0.9682 - val_loss: 0.2557 - val_accuracy: 0.8772
Epoch 72/150
18/18 [==============================] - 0s 4ms/step - loss: 0.1147 - accuracy: 0.9509 - val_loss: 0.2209 - val_accuracy: 0.8830
Epoch 73/150
18/18 [==============================] - 0s 4ms/step - loss: 0.0955 - accuracy: 0.9653 - val_loss: 0.1626 - val_accuracy: 0.9532
Epoch 74/150
18/18 [==============================] - 0s 5ms/step - loss: 0.1124 - accuracy: 0.9653 - val_loss: 0.2168 - val_accuracy: 0.8830
Epoch 75/150
18/18 [==============================] - 0s 4ms/step - loss: 0.0973 - accuracy: 0.9769 - val_loss: 0.2618 - val_accuracy: 0.8772
Epoch 76/150
18/18 [==============================] - 0s 4ms/step - loss: 0.1022 - accuracy: 0.9653 - val_loss: 0.2102 - val_accuracy: 0.8830
Epoch 77/150
18/18 [==============================] - 0s 4ms/step - loss: 0.0889 - accuracy: 0.9769 - val_loss: 0.1565 - val_accuracy: 0.9415
Epoch 78/150
18/18 [==============================] - 0s 4ms/step - loss: 0.0984 - accuracy: 0.9740 - val_loss: 0.1689 - val_accuracy: 0.9123
Epoch 79/150
18/18 [==============================] - 0s 4ms/step - loss: 0.0880 - accuracy: 0.9711 - val_loss: 0.1586 - val_accuracy: 0.9415
Epoch 80/150
18/18 [==============================] - 0s 4ms/step - loss: 0.0859 - accuracy: 0.9769 - val_loss: 0.1635 - val_accuracy: 0.9181
Epoch 81/150
18/18 [==============================] - 0s 4ms/step - loss: 0.0849 - accuracy: 0.9740 - val_loss: 0.1863 - val_accuracy: 0.9006
Epoch 82/150
18/18 [==============================] - 0s 5ms/step - loss: 0.0805 - accuracy: 0.9827 - val_loss: 0.1878 - val_accuracy: 0.9006
Epoch 83/150
18/18 [==============================] - 0s 4ms/step - loss: 0.0946 - accuracy: 0.9682 - val_loss: 0.2545 - val_accuracy: 0.8772
Epoch 84/150
18/18 [==============================] - 0s 4ms/step - loss: 0.0921 - accuracy: 0.9740 - val_loss: 0.1668 - val_accuracy: 0.9123
Epoch 85/150
18/18 [==============================] - 0s 5ms/step - loss: 0.0879 - accuracy: 0.9740 - val_loss: 0.1469 - val_accuracy: 0.9474
Epoch 86/150
18/18 [==============================] - 0s 4ms/step - loss: 0.0874 - accuracy: 0.9740 - val_loss: 0.1465 - val_accuracy: 0.9474
Epoch 87/150
18/18 [==============================] - 0s 4ms/step - loss: 0.1001 - accuracy: 0.9624 - val_loss: 0.1447 - val_accuracy: 0.9415
Epoch 88/150
18/18 [==============================] - 0s 4ms/step - loss: 0.0982 - accuracy: 0.9653 - val_loss: 0.1406 - val_accuracy: 0.9474
Epoch 89/150
18/18 [==============================] - 0s 4ms/step - loss: 0.1051 - accuracy: 0.9624 - val_loss: 0.5410 - val_accuracy: 0.8480
Epoch 90/150
18/18 [==============================] - 0s 7ms/step - loss: 0.1598 - accuracy: 0.9335 - val_loss: 0.2503 - val_accuracy: 0.8830
Epoch 91/150
18/18 [==============================] - 0s 8ms/step - loss: 0.0839 - accuracy: 0.9653 - val_loss: 0.1961 - val_accuracy: 0.8947
Epoch 92/150
18/18 [==============================] - 0s 12ms/step - loss: 0.0735 - accuracy: 0.9740 - val_loss: 0.2272 - val_accuracy: 0.8830
Epoch 93/150
18/18 [==============================] - 0s 10ms/step - loss: 0.0709 - accuracy: 0.9855 - val_loss: 0.2475 - val_accuracy: 0.8830
Epoch 94/150
18/18 [==============================] - 0s 6ms/step - loss: 0.0979 - accuracy: 0.9653 - val_loss: 0.2031 - val_accuracy: 0.8830
Epoch 95/150
18/18 [==============================] - 0s 4ms/step - loss: 0.0724 - accuracy: 0.9769 - val_loss: 0.1888 - val_accuracy: 0.9006
Epoch 96/150
18/18 [==============================] - 0s 4ms/step - loss: 0.0739 - accuracy: 0.9769 - val_loss: 0.1425 - val_accuracy: 0.9415
Epoch 97/150
18/18 [==============================] - 0s 7ms/step - loss: 0.0744 - accuracy: 0.9827 - val_loss: 0.1789 - val_accuracy: 0.9006
Epoch 98/150
18/18 [==============================] - 0s 10ms/step - loss: 0.0715 - accuracy: 0.9798 - val_loss: 0.1443 - val_accuracy: 0.9357
Epoch 99/150
18/18 [==============================] - 0s 10ms/step - loss: 0.0699 - accuracy: 0.9769 - val_loss: 0.1356 - val_accuracy: 0.9415
Epoch 100/150
18/18 [==============================] - 0s 8ms/step - loss: 0.0759 - accuracy: 0.9827 - val_loss: 0.1707 - val_accuracy: 0.9006
Epoch 101/150
18/18 [==============================] - 0s 7ms/step - loss: 0.0722 - accuracy: 0.9798 - val_loss: 0.1401 - val_accuracy: 0.9532
Epoch 102/150
18/18 [==============================] - 0s 9ms/step - loss: 0.0651 - accuracy: 0.9769 - val_loss: 0.1426 - val_accuracy: 0.9357
Epoch 103/150
18/18 [==============================] - 0s 12ms/step - loss: 0.0637 - accuracy: 0.9827 - val_loss: 0.1266 - val_accuracy: 0.9591
Epoch 104/150
18/18 [==============================] - 0s 25ms/step - loss: 0.0655 - accuracy: 0.9798 - val_loss: 0.2067 - val_accuracy: 0.8889
Epoch 105/150
18/18 [==============================] - 0s 14ms/step - loss: 0.0713 - accuracy: 0.9769 - val_loss: 0.1235 - val_accuracy: 0.9591
Epoch 106/150
18/18 [==============================] - 0s 16ms/step - loss: 0.0660 - accuracy: 0.9855 - val_loss: 0.1298 - val_accuracy: 0.9415
Epoch 107/150
18/18 [==============================] - 0s 17ms/step - loss: 0.0701 - accuracy: 0.9827 - val_loss: 0.1225 - val_accuracy: 0.9591
Epoch 108/150
18/18 [==============================] - 0s 16ms/step - loss: 0.1176 - accuracy: 0.9509 - val_loss: 0.1696 - val_accuracy: 0.9006
Epoch 109/150
18/18 [==============================] - 0s 16ms/step - loss: 0.0951 - accuracy: 0.9682 - val_loss: 0.3142 - val_accuracy: 0.8772
Epoch 110/150
18/18 [==============================] - 0s 14ms/step - loss: 0.0885 - accuracy: 0.9711 - val_loss: 0.1956 - val_accuracy: 0.9064
Epoch 111/150
18/18 [==============================] - 0s 28ms/step - loss: 0.0705 - accuracy: 0.9798 - val_loss: 0.1410 - val_accuracy: 0.9591
Epoch 112/150
18/18 [==============================] - 0s 19ms/step - loss: 0.0790 - accuracy: 0.9769 - val_loss: 0.1587 - val_accuracy: 0.9240
Epoch 113/150
18/18 [==============================] - 0s 6ms/step - loss: 0.0778 - accuracy: 0.9769 - val_loss: 0.1717 - val_accuracy: 0.9064
Epoch 114/150
18/18 [==============================] - 0s 4ms/step - loss: 0.0715 - accuracy: 0.9624 - val_loss: 0.1311 - val_accuracy: 0.9649
Epoch 115/150
18/18 [==============================] - 0s 4ms/step - loss: 0.0816 - accuracy: 0.9798 - val_loss: 0.1157 - val_accuracy: 0.9591
Epoch 116/150
18/18 [==============================] - 0s 4ms/step - loss: 0.0544 - accuracy: 0.9884 - val_loss: 0.1168 - val_accuracy: 0.9649
Epoch 117/150
18/18 [==============================] - 0s 5ms/step - loss: 0.0653 - accuracy: 0.9769 - val_loss: 0.1378 - val_accuracy: 0.9357
Epoch 118/150
18/18 [==============================] - 0s 4ms/step - loss: 0.0686 - accuracy: 0.9740 - val_loss: 0.1208 - val_accuracy: 0.9591
Epoch 119/150
18/18 [==============================] - 0s 5ms/step - loss: 0.0646 - accuracy: 0.9769 - val_loss: 0.1966 - val_accuracy: 0.9064
Epoch 120/150
18/18 [==============================] - 0s 4ms/step - loss: 0.0529 - accuracy: 0.9827 - val_loss: 0.1397 - val_accuracy: 0.9357
Epoch 121/150
18/18 [==============================] - 0s 4ms/step - loss: 0.0527 - accuracy: 0.9884 - val_loss: 0.1330 - val_accuracy: 0.9357
Epoch 122/150
18/18 [==============================] - 0s 4ms/step - loss: 0.0490 - accuracy: 0.9884 - val_loss: 0.2428 - val_accuracy: 0.8889
Epoch 123/150
18/18 [==============================] - 0s 4ms/step - loss: 0.0585 - accuracy: 0.9769 - val_loss: 0.1147 - val_accuracy: 0.9591
Epoch 124/150
18/18 [==============================] - 0s 5ms/step - loss: 0.0527 - accuracy: 0.9855 - val_loss: 0.1201 - val_accuracy: 0.9591
Epoch 125/150
18/18 [==============================] - 0s 5ms/step - loss: 0.0489 - accuracy: 0.9855 - val_loss: 0.1853 - val_accuracy: 0.9064
Epoch 126/150
18/18 [==============================] - 0s 5ms/step - loss: 0.0813 - accuracy: 0.9653 - val_loss: 0.1127 - val_accuracy: 0.9532
Epoch 127/150
18/18 [==============================] - 0s 4ms/step - loss: 0.0551 - accuracy: 0.9798 - val_loss: 0.1327 - val_accuracy: 0.9415
Epoch 128/150
18/18 [==============================] - 0s 5ms/step - loss: 0.0569 - accuracy: 0.9798 - val_loss: 0.1436 - val_accuracy: 0.9357
Epoch 129/150
18/18 [==============================] - 0s 5ms/step - loss: 0.0496 - accuracy: 0.9827 - val_loss: 0.1246 - val_accuracy: 0.9474
Epoch 130/150
18/18 [==============================] - 0s 4ms/step - loss: 0.0476 - accuracy: 0.9884 - val_loss: 0.1483 - val_accuracy: 0.9298
Epoch 131/150
18/18 [==============================] - 0s 4ms/step - loss: 0.0604 - accuracy: 0.9855 - val_loss: 0.2212 - val_accuracy: 0.8947
Epoch 132/150
18/18 [==============================] - 0s 4ms/step - loss: 0.0986 - accuracy: 0.9566 - val_loss: 0.4385 - val_accuracy: 0.8772
Epoch 133/150
18/18 [==============================] - 0s 4ms/step - loss: 0.0941 - accuracy: 0.9653 - val_loss: 0.2104 - val_accuracy: 0.9006
Epoch 134/150
18/18 [==============================] - 0s 5ms/step - loss: 0.0649 - accuracy: 0.9798 - val_loss: 0.1061 - val_accuracy: 0.9649
Epoch 135/150
18/18 [==============================] - 0s 10ms/step - loss: 0.0481 - accuracy: 0.9855 - val_loss: 0.1062 - val_accuracy: 0.9474
Epoch 136/150
18/18 [==============================] - 0s 9ms/step - loss: 0.0523 - accuracy: 0.9827 - val_loss: 0.1039 - val_accuracy: 0.9591
Epoch 137/150
18/18 [==============================] - 0s 10ms/step - loss: 0.0470 - accuracy: 0.9884 - val_loss: 0.1639 - val_accuracy: 0.9298
Epoch 138/150
18/18 [==============================] - 0s 7ms/step - loss: 0.0523 - accuracy: 0.9827 - val_loss: 0.1238 - val_accuracy: 0.9474
Epoch 139/150
18/18 [==============================] - 0s 5ms/step - loss: 0.0518 - accuracy: 0.9884 - val_loss: 0.1311 - val_accuracy: 0.9357
Epoch 140/150
18/18 [==============================] - 0s 4ms/step - loss: 0.0531 - accuracy: 0.9769 - val_loss: 0.2088 - val_accuracy: 0.9006
Epoch 141/150

In [19]:
score = model.evaluate(x,y)
print((model.metrics_names[1]))

17/17 [==============================] - 0s 2ms/step - loss: 0.0600 - accuracy: 0.9826
accuracy